version: '3'

services:
 app:
  build: ./app
  container_name: myapp

 nginx:
  image: nginx
  container_name: mynginx
  ports:
   - "${APP_PORT}:80"
   - ."Hello from volue!" > nginx_data/index.html
