name: My First CI

on: [push]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Клонируем репозиторий
      uses: actions/checkout@v3

    - name: 📋 Проверяем наличие .txt файла
      run: |
        echo "Список txt-файлов:"
        ls *.txt || echo "Нет txt-файлов в корне репозитория"

    - name: ✅ Готово
      run: echo "CI-пайплайн завершён успешно!"
